version: '2'

services:
  node-red:
    container_name: node-red
    image: nodered/node-red:1.2.6
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    volumes:
      - /home/pi/.node-red:/data
    network_mode: host

  broker:
    container_name: eclipse-mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    network_mode: host
    
