version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: eclipse-mosquitto-2.0
    restart: unless-stopped
    volumes:
      - /home/pi/Documents/mosquitto-data:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.22.0
    container_name: zigbee2mqtt-1.22.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    volumes:
      - /home/pi/Documents/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

  node-red:
    container_name: node-red-2.1.3
    image: nodered/node-red:2.1.3
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    volumes:
      - node-red-data:/data
    network_mode: host

volumes:
  node-red-data:
