version: '3.7'
services:
  mqtt:
    image: eclipse-mosquitto:2.0.20
    container_name: eclipse-mosquitto-2.0.20
    restart: unless-stopped
    volumes:
      - /home/pi/Documents/domo-server-persist/mosquitto-data:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.42.0
    container_name: zigbee2mqtt-1.42.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    volumes:
      - /home/pi/Documents/domo-server-persist/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  node-red:
    image: nodered/node-red:4.0.8
    container_name: node-red-4.0.8
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    volumes:
      - /home/pi/Documents/domo-server-persist/node-red-data:/data
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  #  node-red-contrib-debounce@0.0.2
  #  node-red-contrib-homekit-bridged@1.7.2
  #  node-red-contrib-melcloud@1.6.0
  #  node-red-contrib-moment@5.0.0
  #  node-red-dashboard@3.6.5
  #  node-red-node-ping@0.3.3

  netdata:
    image: netdata/netdata:v1.45.3
    container_name: netdata-1.45.3
    pid: host
    network_mode: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  bwalink:
    image: ghcr.io/emilletfr/bwalink:latest
    container_name: bwalink
    restart: unless-stopped
    environment:
      # See https://iotbyhvm.ooo/using-uris-to-connect-to-a-mqtt-server/ for MQTT_URI format
      # MQTT_URI *must* be properly URI encoded, e.g. mqtt://useename:pa##word@10.1.10.2 would 
      # be mqtt://username:pa%23%23word@10.1.10.2
      # BRIDGE_IP and BRIDGE_PORT are the address and port for your serial to IP device or 
      # host running ser2net, socat or ESPEasy serial server
      MQTT_URI: mqtt://192.168.8.10
      BRIDGE_IP: 192.168.8.11
      BRIDGE_PORT: 8899
      TZ: Europe/Paris 
      LOG_LEVEL: WARN # Any of FATAL, ERROR, WARN, INFO or DEBUG
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
