version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0.14
    container_name: eclipse-mosquitto-2.0.14
    restart: unless-stopped
    volumes:
      - /home/pi/Documents/domo-server-persist/mosquitto-data:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.22.2
    container_name: zigbee2mqtt-1.22.2
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    volumes:
      - /home/pi/Documents/domo-server-persist/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

  node-red:
    image: nodered/node-red:2.2.2
    container_name: node-red-2.2.2
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    entrypoint: []
    command: bash -c "
      npm install node-red-contrib-debounce && 
      npm install node-red-contrib-homekit-bridged && 
      npm install node-red-contrib-moment && 
      npm install node-red-dashboard && 
      npm install node-red-node-email && 
      npm install node-red-node-ping && 
      node -v &&  node node_modules/node-red/red.js"
    volumes:
      - /home/pi/Documents/domo-server-persist/node-red-data:/data
      - /home/pi/Documents/domo-server-persist:/home/domo-server-persist
    network_mode: host
    
